const Map<String , String > ar ={
  "Please enter your email" : 'الرجاء أدخل بريدك الالكتروني',
  "Please enter valid email" : 'الرجاء أدخل البريد الحقيقي',
  "Please enter your password" : 'الرجاء أدخل كلمة السر الخاصة بك',
  "Password is too short" : 'كلمة السر قصيرة جداً',
  "Passwords don't match" : 'كلمة السر غير مطابقة',
  "Please enter your name" :'الرجاء أدخل اسمك',
  "Please enter your phone number" : 'الرجاء أدخل الرقم الخاص بك',
  "Please enter your address" :'الرجاء أدخل عنزان البريد الالكتروني الخاصة بك',

  'Are you sure you want to exit the form? Any changes will be lost.' : 'هل أنت متأكد من أنك تريد الخروج من الاستبيان؟ ستفقد بعض التغييرات.',
  'Cancel' : 'إلغاء',
  'Confirm' : 'تأكيد',
  'SIGN IN' : 'تسجيل الدخول',
  'Email Address' : 'عنوان البريد الالكتروني',
  "Enter your email" : 'أدخل عنوان بريدك الالكتروني',
  'Password' : 'كلمة السر' ,
  "Remember me" : 'تذكرني',
  'Forgot your password?' : 'هل نسيت كلمة السر؟',
  "Forgot Password" : 'نسيت كلمة السر',
  "Please enter your email and we will send \nyou a link to return your account" :'الرجاء إدخال البريد الالكتروني الخاص بك\n ونحن سنقوم بإرسال رابط لاستعادة حسابك',
  "Enter your password" : 'أدخل كلمة السر الخاصة بك',
  "Continue" : 'متابعة',
  'Don\'t have an account?' : 'ليس لديك حساب؟',
  "Re-enter your password":'أعد إدخال كلمة السر',
  'sign up' : 'إنشاء حساب',
  'SIGN UP' : 'إنشاء حساب',
  'Confirmation Code' : 'إدخال الرمز',
  'We sent you a verification code' : 'لقد أرسلنا لك رمز التحقق',
  'You didn\'t receive the code?' : 'لم يصلك رمز التحقق؟',
  " Try new Code" : 'جرب رمز جديد',
  "Product by categories" : 'منتجات كل صنف',
  'Electronics' : 'الكترونيات',
  'Jewelery' : 'مجوهرات',
  'Men clothing' : 'ملابس رجال',
  'Women clothing' : 'ملابس نساء',
  'Setting' : 'إعدادات',
  'My Cart' : 'السلة',
  'My Purchases' : 'المشتريات',
  'My Activities' : 'سجل النشاطات',
  'About' : 'حول',
  "Log out":'تسجيل خروج',
  'Change Password' : 'تغيير كلمة السر',
  'buy 1 products' : 'شراء 1 منتج',
  'Old Password' : 'كلمة السر القديمة',
  'New Password' : 'كلمة السر الجديدة',
  'Confirm Password' : 'تأكيد كلمة السر',
  'Change Language' : 'تغيير اللغة',
  'Version' : 'الإصدار',
  'Share This app' : 'مشاركة هذا التطبيق',
  'Success' : 'تم',
  "Login Success":'تم تسجيل الدخول بنجاح',
  "Back To Home":'الرجوع',
  'The products have been purchased successfully' : 'تم شراء المنتجات بنجاح',
  "OK" : 'موافق',
  "Delete Confirmation" : 'تأكيد الحذف',
  "Are you sure you want to delete this item?" :'هل أنت متأكد من أنك تريد حذف هذا العنصر؟',
  "Delete" : 'حذف',
  "Total" : 'الحساب الإجمالي',
  "Add to Cart" : 'إضافة إلى السلة',
  "Complete Profile" : 'المعلومات الشخصية',
  "Complete your details or continue \nwith social media" : 'أكمل المعلومات الشخصية الخاصة بك أو \n تابع باستخدام مواقع التواصل الاجتماعي',
  "By continuing your confirm that you agree \nwith our term and condition":'من خلال الاستمرار في تأكيد موافقتك على البنود والشروط الخاصة بنا',
  "First Name":'الاسم الأول',
  "Enter your first name":'أدخل اسمك الأول',
  "Last Name":"الاسم الأخير",
  "Enter your last name":"أدخل اسمك الأخير",
  "Phone Number":"رقم الهاتف",
  "Enter your phone number":"أدخل رقم الهانف الخاص بك",
  "Address":"العنوان",
  "Enter your address":"أدخل عنوانك",
  "Email":"البريد الالكتروني",
};