const Map<String , String > ar ={
  'Are you sure you want to exit the form? Any changes will be lost.' : 'هل أنت متأكد من أنك تريد الخروج من الاستبيان؟ ستفقد أيا تغييرات.',
  'Cancel' : 'إلغاء',
  'Confirm' : 'تأكيد',
  'SIGN IN' : 'تسجيل الدخول',
  'Email Address' : 'عنوان البريد الالكتروني',
  "Enter your email" : 'أدخل عنوان بريدك الالكتروني',
  'Password' : 'كلمة السر' ,
  "Remember me" : 'تذكرني',
  'Forgot your password?' : 'هل نسيت كلمة السر؟',
  "Enter your password" : 'أدخل طلمة السر',
  'Don\'t have an account?' : 'ليس لديك حساب؟',
  'sign up' : 'إنشاء حساب',
  'SIGN UP' : 'إنشاء حساب',
  'Confirmation Code' : 'إدخال الرمز',
  'We sent you a verification code' : 'لقد أرسلنا لك رمز التحقق',
  'You didn\'t receive the code?' : 'لم يصلك رمز التحقق؟',
  " Try new Code" : 'جرب رمز جديد',
  "Product by categories" : 'منتجات كل صنف',
  'Electronics' : 'الكترونيات',
  'Jewelery' : 'مجوهرات',
  'Men clothing' : 'ملابس رجال',
  'Women clothing' : 'ملابس نساء',
  'Setting' : 'إعدادات',
  'My Cart' : 'السلة',
  'My Purchases' : 'المشتريات',
  'My Activities' : 'سجل النشاطات',
  'About' : 'حول',
  'Change Password' : 'تغيير كلمة السر',
  'buy 1 products' : 'شراء 1 منتج',
  'Old Password' : 'كلمة السر القديمة',
  'New Password' : 'كلمة السر الجديدة',
  'Confirm Password' : 'تأكيد كلمة السر',
  'Change Language' : 'تغيير اللغة'
};