const Map<String , String > en ={
  "Please enter your email" :"Please enter your email",
  "Please enter valid email" :"Please enter valid email",
  "Please enter your password" :"Please enter your password",
  "Password is too short" :"Password is too short",
  "Passwords don't match" :"Passwords don't match",
  "Please enter your name" : "Please enter your name",
  "Please enter your phone number" :"Please enter your phone number",
  "Please enter your address" :"Please enter your address",

  'Are you sure you want to exit the form? Any changes will be lost.' : 'Are you sure you want to exit the form? Any changes will be lost.',
  'Cancel' : 'Cancel',
  'Confirm' : 'Confirm',
  'SIGN IN' : 'SIGN IN',
  'Email Address' : 'Email Address',
  "Enter your email" : "Enter your email",
  "Continue" :"Continue",
  'Password' : 'Password' ,
  'Forgot your password?' : 'Forgot your password?',
  "Forgot Password":"Forgot Password",
  "Please enter your email and we will send \nyou a link to return your account":"Please enter your email and we will send \nyou a link to return your account",
  "Enter your password" : "Enter your password",
  'Don\'t have an account?' : 'Don\'t have an account?',
  "Re-enter your password":"Re-enter your password",
  'sign up' : 'sign up',
  'SIGN UP' : 'SIGN UP',
  'Confirmation Code' : 'Confirmation Code',
  'We sent you a verification code' :'We sent you a verification code',
  'You didn\'t receive the code?' :'You didn\'t receive the code?',
  " Try new Code" : " Try new Code",
  "Product by categories" :"Product by categories",
  'Electronics' : 'Electronics',
  'Jewelery' : 'Jewelery',
  'Men clothing' : 'Men clothing',
  'Women clothing' : 'Women clothing',
  'Setting' : 'Setting',
  'My Cart' : 'My Cart',
  'My Purchases' :'My Purchases',
  'My Activities' : 'My Activities',
  'About' : 'About',
  "Log out":"Log out",
  'Change Password' : 'Change Password',
  'buy 1 products' : 'buy 1 products',
  'Old Password' : 'Old Password',
  'New Password' : 'New Password',
  'Confirm Password' : 'Confirm Password',
  'Change Language' : 'Change Language',
  'Version' :'Version',
  'Share This app' :'Share This app',
  'Success' :'Success',
  "Login Success":"Login Success",
  "Back To Home" :"Back To Home",
  'The products have been purchased successfully' :'The products have been purchased successfully',
  "OK" : "OK",
  "Delete Confirmation" : "Delete Confirmation",
  "Are you sure you want to delete this item?" : "Are you sure you want to delete this item?",
  "Delete" :"Delete",
  "Total" : "Total",
  "Add to Cart" : "Add to Cart",
  "Complete Profile":"Complete Profile",
  "Complete your details or continue \nwith social media":"Complete your details or continue \nwith social media",
  "By continuing your confirm that you agree \nwith our term and condition":"By continuing your confirm that you agree \nwith our term and condition",
  "First Name" :"First Name",
  "Enter your first name":"Enter your first name",
  "Last Name":"Last Name",
  "Enter your last name":"Enter your last name",
  "Phone Number":"Phone Number",
  "Enter your phone number":"Enter your phone number",
  "Address":"Address",
  "Enter your address":"Enter your address",
  "Email":"Email",
};