const Map<String , String > en ={
  'Are you sure you want to exit the form? Any changes will be lost.' : 'Are you sure you want to exit the form? Any changes will be lost.',
  'Cancel' : 'Cancel',
  'Confirm' : 'Confirm',
  'SIGN IN' : 'SIGN IN',
  'Email Address' : 'Email Address',
  "Enter your email" : "Enter your email",
  'Password' : 'Password' ,
  'Forgot your password?' : 'Forgot your password?',
  "Enter your password" : "Enter your password",
  'Don\'t have an account?' : 'Don\'t have an account?',
  'sign up' : 'sign up',
  'SIGN UP' : 'SIGN UP',
  'Confirmation Code' : 'Confirmation Code',
  'We sent you a verification code' :'We sent you a verification code',
  'You didn\'t receive the code?' :'You didn\'t receive the code?',
  " Try new Code" : " Try new Code",
  "Product by categories" :"Product by categories",
  'Electronics' : 'Electronics',
  'Jewelery' : 'Jewelery',
  'Men clothing' : 'Men clothing',
  'Women clothing' : 'Women clothing',
  'Setting' : 'Setting',
  'My Cart' : 'My Cart',
  'My Purchases' :'My Purchases',
  'My Activities' : 'My Activities',
  'About' : 'About',
  'Change Password' : 'Change Password',
  'buy 1 products' : 'buy 1 products',
  'Old Password' : 'Old Password',
  'New Password' : 'New Password',
  'Confirm Password' : 'Confirm Password',
  'Change Language' : 'Change Language'
};